import './globals.css'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'

import { ReactNode } from 'react'
import { Roboto_Flex as Roboto } from 'next/font/google'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata = {
  title: 'v1nni7.dev',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" id="html-scroll">
      <body
        className={`${roboto.variable} relative bg-zinc-900 font-sans text-zinc-200`}
      >
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  )
}
